stages:
  process_data:
    cmd: python process_data.py
    deps:
    - process_data.py
    - data/data_raw.csv
    outs:
    - data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cache: false